.TH man 1 "17 November 2018" "1.0" "chkascii man page"

.SH NAME
chkascii \- a small C program that checks an ASCII file for any invalid
characters

.SH SYNOPSIS
chkascii treats valid ASCII values as the set :

{ 32-126 / 9 (horizontal tab) / 10 (line feed a.k.a. Unix newline) }

Anything else is considered junk, although the user can pass in
additional ASCII values to treat as good.

If a text file is otherwise good, chkascii will additionally check
whether the file is properly EOL-terminated. If the file is not
EOL-terminated, chkascii treats it as an error at par with junk.

.SH USAGE
The command below asks myfile to be checked as per the built-in scheme:

chkascii myfile

The command below asks ASCII value 13 (CR) to be treated as good:

chkascii --accept=13 myfile

The command below asks ASCII values 13 (CR) and 11 (VT) to be treated
as good:

chkascii --accept=13,11 myfile

.SH RETURN VALUES
If the file contains good ASCII values (or is empty), 0 is returned.

If the file is good but not EOL-terminated, 1 is returned.
1 is also returned for operational failure.

If the file has junk, -1 is returned. Because the operating system might
map return values to unsigned char, this could return 255 to the shell.
The important point is that if a file has junk, the shell receives a
value other than 0 as well as other than 1.

.SH SEE ALSO
vim(1) has the Normal command ga which displays the ASCII value of the
character under the cursor.

unix2dos(1) converts text files between Unix and DOS line-endings.

.SH BUGS
chkascii does not read standard input, nor are multiple files accepted.

.SH AUTHOR
Manish Jain (bourne.identity@hotmail.com)
